"""add sample_set, subset, image tables

Revision ID: 0857cb6ea4aa
Revises: 5f79415f04f7
Create Date: 2026-04-11 22:32:03.792777

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0857cb6ea4aa"
down_revision: str | Sequence[str] | None = "5f79415f04f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sampleset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("folder_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sampleset", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sampleset_folder_id"),
            ["folder_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sampleset_owner_id"),
            ["owner_id"],
            unique=False,
        )

    op.create_table(
        "subset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sample_set_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("source_module", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_subset_id", sa.Uuid(), nullable=True),
        sa.Column("source_params", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sample_set_id"],
            ["sampleset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_subset_id"],
            ["subset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subset", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subset_sample_set_id"),
            ["sample_set_id"],
            unique=False,
        )

    op.create_table(
        "image",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "format", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("storage_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_image_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_image_id"],
            ["image.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subset_id"],
            ["subset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_image_subset_id"),
            ["subset_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_subset_id"))

    op.drop_table("image")
    with op.batch_alter_table("subset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subset_sample_set_id"))

    op.drop_table("subset")
    with op.batch_alter_table("sampleset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sampleset_owner_id"))
        batch_op.drop_index(batch_op.f("ix_sampleset_folder_id"))

    op.drop_table("sampleset")
    # ### end Alembic commands ###
