"""add task table

Revision ID: 2c85b1f22a97
Revises: e87b65b2013f
Create Date: 2026-04-11 23:51:24.067796

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c85b1f22a97"
down_revision: str | Sequence[str] | None = "e87b65b2013f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "module_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("sample_set_id", sa.Uuid(), nullable=False),
        sa.Column("input_subset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "output_subset_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "loading",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="taskstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "error_message",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["input_subset_id"],
            ["subset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_set_id"],
            ["sampleset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_sample_set_id"),
            ["sample_set_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_task_user_id"),
            ["user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_user_id"))
        batch_op.drop_index(batch_op.f("ix_task_sample_set_id"))

    op.drop_table("task")
    # ### end Alembic commands ###
