"""add subset name unique constraint and task overwrite field

Revision ID: dbd4610d6537
Revises: 2c85b1f22a97
Create Date: 2026-04-13 20:32:05.535364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd4610d6537'
down_revision: Union[str, Sequence[str], None] = '2c85b1f22a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subset', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_subset_sample_set_name', ['sample_set_id', 'name'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overwrite', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('overwrite')

    with op.batch_alter_table('subset', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subset_sample_set_name', type_='unique')

    # ### end Alembic commands ###
