"""add folder and share tables

Revision ID: e87b65b2013f
Revises: 0857cb6ea4aa
Create Date: 2026-04-11 23:02:37.668824

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e87b65b2013f"
down_revision: str | Sequence[str] | None = "0857cb6ea4aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folder",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folder.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("folder", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_folder_owner_id"),
            ["owner_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_folder_parent_id"),
            ["parent_id"],
            unique=False,
        )

    op.create_table(
        "share",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sample_set_id", sa.Uuid(), nullable=False),
        sa.Column("shared_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sample_set_id"],
            ["sampleset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shared_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("share", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_share_sample_set_id"),
            ["sample_set_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_share_shared_by"),
            ["shared_by"],
            unique=False,
        )

    with op.batch_alter_table("sampleset", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_sampleset_folder_id", "folder", ["folder_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sampleset", schema=None) as batch_op:
        batch_op.drop_constraint("fk_sampleset_folder_id", type_="foreignkey")

    with op.batch_alter_table("share", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_share_shared_by"))
        batch_op.drop_index(batch_op.f("ix_share_sample_set_id"))

    op.drop_table("share")
    with op.batch_alter_table("folder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_folder_parent_id"))
        batch_op.drop_index(batch_op.f("ix_folder_owner_id"))

    op.drop_table("folder")
    # ### end Alembic commands ###
