// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5201' | (string & {});
};

/**
 * AdminSampleSetRead
 */
export type AdminSampleSetRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Folder Id
     */
    folder_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Owner Username
     */
    owner_username: string;
};

/**
 * AdminUserCreate
 */
export type AdminUserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Role
     */
    role?: string;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * AdminUserUpdate
 */
export type AdminUserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * AwarenessResponse
 */
export type AwarenessResponse = {
    primary: ModuleAwarenessItem | null;
    /**
     * Suggested
     */
    suggested: Array<ModuleAwarenessItem>;
    /**
     * Available
     */
    available: Array<ModuleAwarenessItem>;
};

/**
 * BatchMoveItem
 */
export type BatchMoveItem = {
    /**
     * Type
     */
    type: 'folder' | 'sample_set';
    /**
     * Id
     */
    id: string;
};

/**
 * BatchMoveRequest
 */
export type BatchMoveRequest = {
    /**
     * Items
     */
    items: Array<BatchMoveItem>;
    /**
     * Target Folder Id
     */
    target_folder_id?: string | null;
};

/**
 * BatchTaskCreate
 */
export type BatchTaskCreate = {
    /**
     * Module Name
     */
    module_name: string;
    /**
     * Sample Set Id
     */
    sample_set_id: string;
    /**
     * Input Subset Ids
     */
    input_subset_ids: Array<string>;
    /**
     * Output Subset Name Template
     */
    output_subset_name_template?: string;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Overwrite
     */
    overwrite?: boolean;
};

/**
 * BatchTaskError
 */
export type BatchTaskError = {
    /**
     * Input Subset Id
     */
    input_subset_id: string;
    /**
     * Error Code
     */
    error_code: number;
    /**
     * Message
     */
    message: string;
};

/**
 * BatchTaskResult
 */
export type BatchTaskResult = {
    /**
     * Tasks
     */
    tasks: Array<TaskRead>;
    /**
     * Errors
     */
    errors: Array<BatchTaskError>;
};

/**
 * Body_upload_api_sample_sets__sample_set_id__subsets__subset_id__images_post
 */
export type BodyUploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BreadcrumbItem
 */
export type BreadcrumbItem = {
    /**
     * Id
     */
    id: string | null;
    /**
     * Name
     */
    name: string;
};

/**
 * FolderCreate
 */
export type FolderCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * FolderRead
 */
export type FolderRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * FolderTreeNode
 */
export type FolderTreeNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Children
     */
    children?: Array<FolderTreeNode>;
    /**
     * Sample Sets
     */
    sample_sets?: Array<TreeSampleSet>;
};

/**
 * FolderUpdate
 */
export type FolderUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageRead
 */
export type ImageRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Subset Id
     */
    subset_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Format
     */
    format: string;
    /**
     * Metadata
     */
    metadata_: {
        [key: string]: unknown;
    };
    /**
     * Storage Path
     */
    storage_path: string;
    /**
     * Source Image Id
     */
    source_image_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ImageUpdate
 */
export type ImageUpdate = {
    /**
     * Filename
     */
    filename?: string | null;
};

/**
 * LibraryContents
 */
export type LibraryContents = {
    /**
     * Folder Id
     */
    folder_id: string | null;
    /**
     * Breadcrumb
     */
    breadcrumb: Array<BreadcrumbItem>;
    /**
     * Items
     */
    items: Array<LibraryItem>;
};

/**
 * LibraryItem
 *
 * A unified item in folder contents (folder or sample_set).
 */
export type LibraryItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: 'folder' | 'sample_set';
    /**
     * Description
     */
    description?: string | null;
    /**
     * Child Count
     */
    child_count?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * LibraryTree
 */
export type LibraryTree = {
    /**
     * Folders
     */
    folders: Array<FolderTreeNode>;
    /**
     * Root Sample Sets
     */
    root_sample_sets: Array<TreeSampleSet>;
};

/**
 * ModuleAwarenessItem
 */
export type ModuleAwarenessItem = {
    /**
     * Module Name
     */
    module_name: string;
    /**
     * Available Subset Ids
     */
    available_subset_ids: Array<string>;
    /**
     * Recommended Subset Ids
     */
    recommended_subset_ids: Array<string>;
    /**
     * Reason
     */
    reason: string | null;
};

/**
 * ModuleInfoRead
 */
export type ModuleInfoRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: string;
    /**
     * Description
     */
    description: string;
    /**
     * Suggestion Priority
     */
    suggestion_priority: number;
    /**
     * Max Ram Mb
     */
    max_ram_mb: number;
    /**
     * Max Vram Mb
     */
    max_vram_mb: number;
    /**
     * Params Schema
     */
    params_schema: {
        [key: string]: unknown;
    } | null;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Loaded
     */
    loaded: boolean;
};

/**
 * ResourceStatusRead
 */
export type ResourceStatusRead = {
    /**
     * Total Ram Mb
     */
    total_ram_mb: number;
    /**
     * Total Vram Mb
     */
    total_vram_mb: number;
    /**
     * Threshold Ratio
     */
    threshold_ratio: number;
    /**
     * Used Ram Mb
     */
    used_ram_mb: number;
    /**
     * Used Vram Mb
     */
    used_vram_mb: number;
    /**
     * Available Ram Mb
     */
    available_ram_mb: number;
    /**
     * Available Vram Mb
     */
    available_vram_mb: number;
    /**
     * Loaded Modules
     */
    loaded_modules: Array<string>;
};

/**
 * SampleSetCreate
 */
export type SampleSetCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
};

/**
 * SampleSetDetail
 */
export type SampleSetDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Folder Id
     */
    folder_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Subsets
     */
    subsets?: Array<SubsetRead>;
    /**
     * Is Shared
     */
    is_shared?: boolean;
    /**
     * Folder Name
     */
    folder_name?: string | null;
};

/**
 * SampleSetRead
 */
export type SampleSetRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Folder Id
     */
    folder_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * SampleSetUpdate
 */
export type SampleSetUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
};

/**
 * SharedSampleSetRead
 */
export type SharedSampleSetRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Sample Set Id
     */
    sample_set_id: string;
    /**
     * Sample Set Name
     */
    sample_set_name: string;
    /**
     * Sample Set Description
     */
    sample_set_description: string | null;
    /**
     * Shared By
     */
    shared_by: string;
    /**
     * Shared By Username
     */
    shared_by_username: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SubsetCreate
 */
export type SubsetCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type?: string;
};

/**
 * SubsetDetail
 */
export type SubsetDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Sample Set Id
     */
    sample_set_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Metadata
     */
    metadata_: {
        [key: string]: unknown;
    };
    /**
     * Source Module
     */
    source_module: string | null;
    /**
     * Source Subset Id
     */
    source_subset_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Images
     */
    images?: Array<ImageRead>;
};

/**
 * SubsetRead
 */
export type SubsetRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Sample Set Id
     */
    sample_set_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Metadata
     */
    metadata_: {
        [key: string]: unknown;
    };
    /**
     * Source Module
     */
    source_module: string | null;
    /**
     * Source Subset Id
     */
    source_subset_id: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SubsetUpdate
 */
export type SubsetUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Module Name
     */
    module_name: string;
    /**
     * Sample Set Id
     */
    sample_set_id: string;
    /**
     * Input Subset Id
     */
    input_subset_id: string;
    /**
     * Output Subset Name
     */
    output_subset_name: string;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Overwrite
     */
    overwrite?: boolean;
};

/**
 * TaskRead
 */
export type TaskRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Module Name
     */
    module_name: string;
    /**
     * Sample Set Id
     */
    sample_set_id: string;
    /**
     * Input Subset Id
     */
    input_subset_id: string;
    /**
     * Output Subset Name
     */
    output_subset_name: string;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    } | null;
    /**
     * Overwrite
     */
    overwrite: boolean;
    status: TaskStatus;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Retry Count
     */
    retry_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Sample Set Name
     */
    sample_set_name?: string | null;
    /**
     * Input Subset Name
     */
    input_subset_name?: string | null;
};

/**
 * TaskStatus
 */
export type TaskStatus = 'queued' | 'loading' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TreeSampleSet
 */
export type TreeSampleSet = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RegisterApiAuthRegisterPostData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterApiAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiAuthRegisterPostError = RegisterApiAuthRegisterPostErrors[keyof RegisterApiAuthRegisterPostErrors];

export type RegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterApiAuthRegisterPostResponse = RegisterApiAuthRegisterPostResponses[keyof RegisterApiAuthRegisterPostResponses];

export type LoginApiAuthLoginPostData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type GetMeApiUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetMeApiUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetMeApiUsersMeGetResponse = GetMeApiUsersMeGetResponses[keyof GetMeApiUsersMeGetResponses];

export type UpdateMeApiUsersMePutData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UpdateMeApiUsersMePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMeApiUsersMePutError = UpdateMeApiUsersMePutErrors[keyof UpdateMeApiUsersMePutErrors];

export type UpdateMeApiUsersMePutResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateMeApiUsersMePutResponse = UpdateMeApiUsersMePutResponses[keyof UpdateMeApiUsersMePutResponses];

export type GetUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetUsersApiUsersGetResponses = {
    /**
     * Response Get Users Api Users Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetUsersApiUsersGetResponse = GetUsersApiUsersGetResponses[keyof GetUsersApiUsersGetResponses];

export type CreateUserApiUsersPostData = {
    body: AdminUserCreate;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserApiUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiUsersPostError = CreateUserApiUsersPostErrors[keyof CreateUserApiUsersPostErrors];

export type CreateUserApiUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type CreateUserApiUsersPostResponse = CreateUserApiUsersPostResponses[keyof CreateUserApiUsersPostResponses];

export type AdminDeleteApiUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type AdminDeleteApiUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteApiUsersUserIdDeleteError = AdminDeleteApiUsersUserIdDeleteErrors[keyof AdminDeleteApiUsersUserIdDeleteErrors];

export type AdminDeleteApiUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AdminDeleteApiUsersUserIdDeleteResponse = AdminDeleteApiUsersUserIdDeleteResponses[keyof AdminDeleteApiUsersUserIdDeleteResponses];

export type AdminUpdateApiUsersUserIdPutData = {
    body: AdminUserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type AdminUpdateApiUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminUpdateApiUsersUserIdPutError = AdminUpdateApiUsersUserIdPutErrors[keyof AdminUpdateApiUsersUserIdPutErrors];

export type AdminUpdateApiUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AdminUpdateApiUsersUserIdPutResponse = AdminUpdateApiUsersUserIdPutResponses[keyof AdminUpdateApiUsersUserIdPutResponses];

export type ListMineApiSampleSetsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sample-sets';
};

export type ListMineApiSampleSetsGetResponses = {
    /**
     * Response List Mine Api Sample Sets Get
     *
     * Successful Response
     */
    200: Array<SampleSetRead>;
};

export type ListMineApiSampleSetsGetResponse = ListMineApiSampleSetsGetResponses[keyof ListMineApiSampleSetsGetResponses];

export type CreateApiSampleSetsPostData = {
    body: SampleSetCreate;
    path?: never;
    query?: never;
    url: '/api/sample-sets';
};

export type CreateApiSampleSetsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiSampleSetsPostError = CreateApiSampleSetsPostErrors[keyof CreateApiSampleSetsPostErrors];

export type CreateApiSampleSetsPostResponses = {
    /**
     * Successful Response
     */
    201: SampleSetRead;
};

export type CreateApiSampleSetsPostResponse = CreateApiSampleSetsPostResponses[keyof CreateApiSampleSetsPostResponses];

export type DeleteApiSampleSetsSampleSetIdDeleteData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}';
};

export type DeleteApiSampleSetsSampleSetIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiSampleSetsSampleSetIdDeleteError = DeleteApiSampleSetsSampleSetIdDeleteErrors[keyof DeleteApiSampleSetsSampleSetIdDeleteErrors];

export type DeleteApiSampleSetsSampleSetIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiSampleSetsSampleSetIdDeleteResponse = DeleteApiSampleSetsSampleSetIdDeleteResponses[keyof DeleteApiSampleSetsSampleSetIdDeleteResponses];

export type GetDetailApiSampleSetsSampleSetIdGetData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}';
};

export type GetDetailApiSampleSetsSampleSetIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDetailApiSampleSetsSampleSetIdGetError = GetDetailApiSampleSetsSampleSetIdGetErrors[keyof GetDetailApiSampleSetsSampleSetIdGetErrors];

export type GetDetailApiSampleSetsSampleSetIdGetResponses = {
    /**
     * Successful Response
     */
    200: SampleSetDetail;
};

export type GetDetailApiSampleSetsSampleSetIdGetResponse = GetDetailApiSampleSetsSampleSetIdGetResponses[keyof GetDetailApiSampleSetsSampleSetIdGetResponses];

export type UpdateApiSampleSetsSampleSetIdPutData = {
    body: SampleSetUpdate;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}';
};

export type UpdateApiSampleSetsSampleSetIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateApiSampleSetsSampleSetIdPutError = UpdateApiSampleSetsSampleSetIdPutErrors[keyof UpdateApiSampleSetsSampleSetIdPutErrors];

export type UpdateApiSampleSetsSampleSetIdPutResponses = {
    /**
     * Successful Response
     */
    200: SampleSetRead;
};

export type UpdateApiSampleSetsSampleSetIdPutResponse = UpdateApiSampleSetsSampleSetIdPutResponses[keyof UpdateApiSampleSetsSampleSetIdPutResponses];

export type ListAllApiSampleSetsSampleSetIdSubsetsGetData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets';
};

export type ListAllApiSampleSetsSampleSetIdSubsetsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAllApiSampleSetsSampleSetIdSubsetsGetError = ListAllApiSampleSetsSampleSetIdSubsetsGetErrors[keyof ListAllApiSampleSetsSampleSetIdSubsetsGetErrors];

export type ListAllApiSampleSetsSampleSetIdSubsetsGetResponses = {
    /**
     * Response List All Api Sample Sets  Sample Set Id  Subsets Get
     *
     * Successful Response
     */
    200: Array<SubsetRead>;
};

export type ListAllApiSampleSetsSampleSetIdSubsetsGetResponse = ListAllApiSampleSetsSampleSetIdSubsetsGetResponses[keyof ListAllApiSampleSetsSampleSetIdSubsetsGetResponses];

export type CreateApiSampleSetsSampleSetIdSubsetsPostData = {
    body: SubsetCreate;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets';
};

export type CreateApiSampleSetsSampleSetIdSubsetsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiSampleSetsSampleSetIdSubsetsPostError = CreateApiSampleSetsSampleSetIdSubsetsPostErrors[keyof CreateApiSampleSetsSampleSetIdSubsetsPostErrors];

export type CreateApiSampleSetsSampleSetIdSubsetsPostResponses = {
    /**
     * Successful Response
     */
    201: SubsetRead;
};

export type CreateApiSampleSetsSampleSetIdSubsetsPostResponse = CreateApiSampleSetsSampleSetIdSubsetsPostResponses[keyof CreateApiSampleSetsSampleSetIdSubsetsPostResponses];

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}';
};

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteError = DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteErrors[keyof DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteErrors];

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteResponse = DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteResponses[keyof DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdDeleteResponses];

export type GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}';
};

export type GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetError = GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetErrors[keyof GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetErrors];

export type GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetResponses = {
    /**
     * Successful Response
     */
    200: SubsetDetail;
};

export type GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetResponse = GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetResponses[keyof GetDetailApiSampleSetsSampleSetIdSubsetsSubsetIdGetResponses];

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutData = {
    body: SubsetUpdate;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}';
};

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutError = UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutErrors[keyof UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutErrors];

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutResponses = {
    /**
     * Successful Response
     */
    200: SubsetRead;
};

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutResponse = UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutResponses[keyof UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdPutResponses];

export type ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}/images';
};

export type ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetError = ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetErrors[keyof ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetErrors];

export type ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetResponses = {
    /**
     * Response List All Api Sample Sets  Sample Set Id  Subsets  Subset Id  Images Get
     *
     * Successful Response
     */
    200: Array<ImageRead>;
};

export type ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetResponse = ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetResponses[keyof ListAllApiSampleSetsSampleSetIdSubsetsSubsetIdImagesGetResponses];

export type UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostData = {
    body: BodyUploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPost;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}/images';
};

export type UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostError = UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostErrors[keyof UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostErrors];

export type UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostResponses = {
    /**
     * Successful Response
     */
    201: ImageRead;
};

export type UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostResponse = UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostResponses[keyof UploadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesPostResponses];

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}/images/{image_id}';
};

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteError = DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteErrors[keyof DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteErrors];

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteResponse = DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteResponses[keyof DeleteApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDeleteResponses];

export type GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}/images/{image_id}';
};

export type GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetError = GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetErrors[keyof GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetErrors];

export type GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetResponses = {
    /**
     * Successful Response
     */
    200: ImageRead;
};

export type GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetResponse = GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetResponses[keyof GetMetaApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdGetResponses];

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutData = {
    body: ImageUpdate;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}/images/{image_id}';
};

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutError = UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutErrors[keyof UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutErrors];

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutResponses = {
    /**
     * Successful Response
     */
    200: ImageRead;
};

export type UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutResponse = UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutResponses[keyof UpdateApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdPutResponses];

export type DownloadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDownloadGetData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
        /**
         * Subset Id
         */
        subset_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/sample-sets/{sample_set_id}/subsets/{subset_id}/images/{image_id}/download';
};

export type DownloadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDownloadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDownloadGetError = DownloadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDownloadGetErrors[keyof DownloadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDownloadGetErrors];

export type DownloadApiSampleSetsSampleSetIdSubsetsSubsetIdImagesImageIdDownloadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ContentsApiLibraryContentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Folder Id
         */
        folder_id?: string | null;
        /**
         * Sort By
         */
        sort_by?: 'name' | 'created_at' | 'updated_at';
        /**
         * Sort Order
         */
        sort_order?: 'asc' | 'desc';
    };
    url: '/api/library/contents';
};

export type ContentsApiLibraryContentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ContentsApiLibraryContentsGetError = ContentsApiLibraryContentsGetErrors[keyof ContentsApiLibraryContentsGetErrors];

export type ContentsApiLibraryContentsGetResponses = {
    /**
     * Successful Response
     */
    200: LibraryContents;
};

export type ContentsApiLibraryContentsGetResponse = ContentsApiLibraryContentsGetResponses[keyof ContentsApiLibraryContentsGetResponses];

export type PathApiLibraryPathFolderIdGetData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/api/library/path/{folder_id}';
};

export type PathApiLibraryPathFolderIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PathApiLibraryPathFolderIdGetError = PathApiLibraryPathFolderIdGetErrors[keyof PathApiLibraryPathFolderIdGetErrors];

export type PathApiLibraryPathFolderIdGetResponses = {
    /**
     * Response Path Api Library Path  Folder Id  Get
     *
     * Successful Response
     */
    200: Array<BreadcrumbItem>;
};

export type PathApiLibraryPathFolderIdGetResponse = PathApiLibraryPathFolderIdGetResponses[keyof PathApiLibraryPathFolderIdGetResponses];

export type TreeApiLibraryTreeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/library/tree';
};

export type TreeApiLibraryTreeGetResponses = {
    /**
     * Successful Response
     */
    200: LibraryTree;
};

export type TreeApiLibraryTreeGetResponse = TreeApiLibraryTreeGetResponses[keyof TreeApiLibraryTreeGetResponses];

export type CreateApiLibraryFoldersPostData = {
    body: FolderCreate;
    path?: never;
    query?: never;
    url: '/api/library/folders';
};

export type CreateApiLibraryFoldersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiLibraryFoldersPostError = CreateApiLibraryFoldersPostErrors[keyof CreateApiLibraryFoldersPostErrors];

export type CreateApiLibraryFoldersPostResponses = {
    /**
     * Successful Response
     */
    201: FolderRead;
};

export type CreateApiLibraryFoldersPostResponse = CreateApiLibraryFoldersPostResponses[keyof CreateApiLibraryFoldersPostResponses];

export type DeleteApiLibraryFoldersFolderIdDeleteData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: {
        /**
         * Recursive
         */
        recursive?: boolean;
    };
    url: '/api/library/folders/{folder_id}';
};

export type DeleteApiLibraryFoldersFolderIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiLibraryFoldersFolderIdDeleteError = DeleteApiLibraryFoldersFolderIdDeleteErrors[keyof DeleteApiLibraryFoldersFolderIdDeleteErrors];

export type DeleteApiLibraryFoldersFolderIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiLibraryFoldersFolderIdDeleteResponse = DeleteApiLibraryFoldersFolderIdDeleteResponses[keyof DeleteApiLibraryFoldersFolderIdDeleteResponses];

export type UpdateApiLibraryFoldersFolderIdPutData = {
    body: FolderUpdate;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/api/library/folders/{folder_id}';
};

export type UpdateApiLibraryFoldersFolderIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateApiLibraryFoldersFolderIdPutError = UpdateApiLibraryFoldersFolderIdPutErrors[keyof UpdateApiLibraryFoldersFolderIdPutErrors];

export type UpdateApiLibraryFoldersFolderIdPutResponses = {
    /**
     * Successful Response
     */
    200: FolderRead;
};

export type UpdateApiLibraryFoldersFolderIdPutResponse = UpdateApiLibraryFoldersFolderIdPutResponses[keyof UpdateApiLibraryFoldersFolderIdPutResponses];

export type BatchMoveApiLibraryBatchMovePostData = {
    body: BatchMoveRequest;
    path?: never;
    query?: never;
    url: '/api/library/batch-move';
};

export type BatchMoveApiLibraryBatchMovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchMoveApiLibraryBatchMovePostError = BatchMoveApiLibraryBatchMovePostErrors[keyof BatchMoveApiLibraryBatchMovePostErrors];

export type BatchMoveApiLibraryBatchMovePostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type BatchMoveApiLibraryBatchMovePostResponse = BatchMoveApiLibraryBatchMovePostResponses[keyof BatchMoveApiLibraryBatchMovePostResponses];

export type ListSharedApiLibrarySharedGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/library/shared';
};

export type ListSharedApiLibrarySharedGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSharedApiLibrarySharedGetError = ListSharedApiLibrarySharedGetErrors[keyof ListSharedApiLibrarySharedGetErrors];

export type ListSharedApiLibrarySharedGetResponses = {
    /**
     * Response List Shared Api Library Shared Get
     *
     * Successful Response
     */
    200: Array<SharedSampleSetRead>;
};

export type ListSharedApiLibrarySharedGetResponse = ListSharedApiLibrarySharedGetResponses[keyof ListSharedApiLibrarySharedGetResponses];

export type UnpublishSharedApiLibrarySharedSampleSetIdDeleteData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/library/shared/{sample_set_id}';
};

export type UnpublishSharedApiLibrarySharedSampleSetIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnpublishSharedApiLibrarySharedSampleSetIdDeleteError = UnpublishSharedApiLibrarySharedSampleSetIdDeleteErrors[keyof UnpublishSharedApiLibrarySharedSampleSetIdDeleteErrors];

export type UnpublishSharedApiLibrarySharedSampleSetIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UnpublishSharedApiLibrarySharedSampleSetIdDeleteResponse = UnpublishSharedApiLibrarySharedSampleSetIdDeleteResponses[keyof UnpublishSharedApiLibrarySharedSampleSetIdDeleteResponses];

export type PublishSharedApiLibrarySharedSampleSetIdPostData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/library/shared/{sample_set_id}';
};

export type PublishSharedApiLibrarySharedSampleSetIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishSharedApiLibrarySharedSampleSetIdPostError = PublishSharedApiLibrarySharedSampleSetIdPostErrors[keyof PublishSharedApiLibrarySharedSampleSetIdPostErrors];

export type PublishSharedApiLibrarySharedSampleSetIdPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type CopySharedApiLibrarySharedSampleSetIdCopyPostData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: {
        /**
         * Folder Id
         */
        folder_id?: string | null;
    };
    url: '/api/library/shared/{sample_set_id}/copy';
};

export type CopySharedApiLibrarySharedSampleSetIdCopyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CopySharedApiLibrarySharedSampleSetIdCopyPostError = CopySharedApiLibrarySharedSampleSetIdCopyPostErrors[keyof CopySharedApiLibrarySharedSampleSetIdCopyPostErrors];

export type CopySharedApiLibrarySharedSampleSetIdCopyPostResponses = {
    /**
     * Successful Response
     */
    201: SampleSetRead;
};

export type CopySharedApiLibrarySharedSampleSetIdCopyPostResponse = CopySharedApiLibrarySharedSampleSetIdCopyPostResponses[keyof CopySharedApiLibrarySharedSampleSetIdCopyPostResponses];

export type ListModulesApiPipelinesModulesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pipelines/modules';
};

export type ListModulesApiPipelinesModulesGetResponses = {
    /**
     * Response List Modules Api Pipelines Modules Get
     *
     * Successful Response
     */
    200: Array<ModuleInfoRead>;
};

export type ListModulesApiPipelinesModulesGetResponse = ListModulesApiPipelinesModulesGetResponses[keyof ListModulesApiPipelinesModulesGetResponses];

export type GetModuleApiPipelinesModulesNameGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/pipelines/modules/{name}';
};

export type GetModuleApiPipelinesModulesNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModuleApiPipelinesModulesNameGetError = GetModuleApiPipelinesModulesNameGetErrors[keyof GetModuleApiPipelinesModulesNameGetErrors];

export type GetModuleApiPipelinesModulesNameGetResponses = {
    /**
     * Successful Response
     */
    200: ModuleInfoRead;
};

export type GetModuleApiPipelinesModulesNameGetResponse = GetModuleApiPipelinesModulesNameGetResponses[keyof GetModuleApiPipelinesModulesNameGetResponses];

export type EnableModuleApiPipelinesModulesNameEnablePutData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/pipelines/modules/{name}/enable';
};

export type EnableModuleApiPipelinesModulesNameEnablePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnableModuleApiPipelinesModulesNameEnablePutError = EnableModuleApiPipelinesModulesNameEnablePutErrors[keyof EnableModuleApiPipelinesModulesNameEnablePutErrors];

export type EnableModuleApiPipelinesModulesNameEnablePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DisableModuleApiPipelinesModulesNameDisablePutData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/pipelines/modules/{name}/disable';
};

export type DisableModuleApiPipelinesModulesNameDisablePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DisableModuleApiPipelinesModulesNameDisablePutError = DisableModuleApiPipelinesModulesNameDisablePutErrors[keyof DisableModuleApiPipelinesModulesNameDisablePutErrors];

export type DisableModuleApiPipelinesModulesNameDisablePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoadModuleApiPipelinesModulesNameLoadPostData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/pipelines/modules/{name}/load';
};

export type LoadModuleApiPipelinesModulesNameLoadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoadModuleApiPipelinesModulesNameLoadPostError = LoadModuleApiPipelinesModulesNameLoadPostErrors[keyof LoadModuleApiPipelinesModulesNameLoadPostErrors];

export type LoadModuleApiPipelinesModulesNameLoadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UnloadModuleApiPipelinesModulesNameUnloadPostData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/pipelines/modules/{name}/unload';
};

export type UnloadModuleApiPipelinesModulesNameUnloadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnloadModuleApiPipelinesModulesNameUnloadPostError = UnloadModuleApiPipelinesModulesNameUnloadPostErrors[keyof UnloadModuleApiPipelinesModulesNameUnloadPostErrors];

export type UnloadModuleApiPipelinesModulesNameUnloadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetResourcesApiPipelinesResourcesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pipelines/resources';
};

export type GetResourcesApiPipelinesResourcesGetResponses = {
    /**
     * Successful Response
     */
    200: ResourceStatusRead;
};

export type GetResourcesApiPipelinesResourcesGetResponse = GetResourcesApiPipelinesResourcesGetResponses[keyof GetResourcesApiPipelinesResourcesGetResponses];

export type GetAwarenessApiPipelinesAwarenessSampleSetIdGetData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/pipelines/awareness/{sample_set_id}';
};

export type GetAwarenessApiPipelinesAwarenessSampleSetIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAwarenessApiPipelinesAwarenessSampleSetIdGetError = GetAwarenessApiPipelinesAwarenessSampleSetIdGetErrors[keyof GetAwarenessApiPipelinesAwarenessSampleSetIdGetErrors];

export type GetAwarenessApiPipelinesAwarenessSampleSetIdGetResponses = {
    /**
     * Successful Response
     */
    200: AwarenessResponse;
};

export type GetAwarenessApiPipelinesAwarenessSampleSetIdGetResponse = GetAwarenessApiPipelinesAwarenessSampleSetIdGetResponses[keyof GetAwarenessApiPipelinesAwarenessSampleSetIdGetResponses];

export type RunPipelineApiPipelinesRunPostData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/api/pipelines/run';
};

export type RunPipelineApiPipelinesRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunPipelineApiPipelinesRunPostError = RunPipelineApiPipelinesRunPostErrors[keyof RunPipelineApiPipelinesRunPostErrors];

export type RunPipelineApiPipelinesRunPostResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type RunPipelineApiPipelinesRunPostResponse = RunPipelineApiPipelinesRunPostResponses[keyof RunPipelineApiPipelinesRunPostResponses];

export type BatchRunPipelineApiPipelinesBatchRunPostData = {
    body: BatchTaskCreate;
    path?: never;
    query?: never;
    url: '/api/pipelines/batch-run';
};

export type BatchRunPipelineApiPipelinesBatchRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchRunPipelineApiPipelinesBatchRunPostError = BatchRunPipelineApiPipelinesBatchRunPostErrors[keyof BatchRunPipelineApiPipelinesBatchRunPostErrors];

export type BatchRunPipelineApiPipelinesBatchRunPostResponses = {
    /**
     * Successful Response
     */
    201: BatchTaskResult;
};

export type BatchRunPipelineApiPipelinesBatchRunPostResponse = BatchRunPipelineApiPipelinesBatchRunPostResponses[keyof BatchRunPipelineApiPipelinesBatchRunPostResponses];

export type ListMyTasksApiTasksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type ListMyTasksApiTasksGetResponses = {
    /**
     * Response List My Tasks Api Tasks Get
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type ListMyTasksApiTasksGetResponse = ListMyTasksApiTasksGetResponses[keyof ListMyTasksApiTasksGetResponses];

export type ListAllApiTasksAllGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/all';
};

export type ListAllApiTasksAllGetResponses = {
    /**
     * Response List All Api Tasks All Get
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type ListAllApiTasksAllGetResponse = ListAllApiTasksAllGetResponses[keyof ListAllApiTasksAllGetResponses];

export type ClearHistoryApiTasksHistoryDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/history';
};

export type ClearHistoryApiTasksHistoryDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteTaskEndpointApiTasksTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type DeleteTaskEndpointApiTasksTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskEndpointApiTasksTaskIdDeleteError = DeleteTaskEndpointApiTasksTaskIdDeleteErrors[keyof DeleteTaskEndpointApiTasksTaskIdDeleteErrors];

export type DeleteTaskEndpointApiTasksTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTaskEndpointApiTasksTaskIdDeleteResponse = DeleteTaskEndpointApiTasksTaskIdDeleteResponses[keyof DeleteTaskEndpointApiTasksTaskIdDeleteResponses];

export type GetTaskDetailApiTasksTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type GetTaskDetailApiTasksTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskDetailApiTasksTaskIdGetError = GetTaskDetailApiTasksTaskIdGetErrors[keyof GetTaskDetailApiTasksTaskIdGetErrors];

export type GetTaskDetailApiTasksTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type GetTaskDetailApiTasksTaskIdGetResponse = GetTaskDetailApiTasksTaskIdGetResponses[keyof GetTaskDetailApiTasksTaskIdGetResponses];

export type CancelTaskEndpointApiTasksTaskIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/cancel';
};

export type CancelTaskEndpointApiTasksTaskIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTaskEndpointApiTasksTaskIdCancelPostError = CancelTaskEndpointApiTasksTaskIdCancelPostErrors[keyof CancelTaskEndpointApiTasksTaskIdCancelPostErrors];

export type CancelTaskEndpointApiTasksTaskIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type CancelTaskEndpointApiTasksTaskIdCancelPostResponse = CancelTaskEndpointApiTasksTaskIdCancelPostResponses[keyof CancelTaskEndpointApiTasksTaskIdCancelPostResponses];

export type ListAllSampleSetsApiAdminSampleSetsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
        /**
         * Owner Id
         */
        owner_id?: string | null;
    };
    url: '/api/admin/sample-sets';
};

export type ListAllSampleSetsApiAdminSampleSetsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAllSampleSetsApiAdminSampleSetsGetError = ListAllSampleSetsApiAdminSampleSetsGetErrors[keyof ListAllSampleSetsApiAdminSampleSetsGetErrors];

export type ListAllSampleSetsApiAdminSampleSetsGetResponses = {
    /**
     * Response List All Sample Sets Api Admin Sample Sets Get
     *
     * Successful Response
     */
    200: Array<AdminSampleSetRead>;
};

export type ListAllSampleSetsApiAdminSampleSetsGetResponse = ListAllSampleSetsApiAdminSampleSetsGetResponses[keyof ListAllSampleSetsApiAdminSampleSetsGetResponses];

export type AdminRemoveSharedApiAdminSharedSampleSetIdDeleteData = {
    body?: never;
    path: {
        /**
         * Sample Set Id
         */
        sample_set_id: string;
    };
    query?: never;
    url: '/api/admin/shared/{sample_set_id}';
};

export type AdminRemoveSharedApiAdminSharedSampleSetIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminRemoveSharedApiAdminSharedSampleSetIdDeleteError = AdminRemoveSharedApiAdminSharedSampleSetIdDeleteErrors[keyof AdminRemoveSharedApiAdminSharedSampleSetIdDeleteErrors];

export type AdminRemoveSharedApiAdminSharedSampleSetIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStatsApiAdminStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/stats';
};

export type GetStatsApiAdminStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
